"""Small wrapper around the official Groq Python SDK."""

import hashlib
import logging
import os
import re
from importlib.metadata import version
from typing import Any

import groq
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

logger = logging.getLogger(__name__)
GROQ_MODEL = "openai/gpt-oss-20b"
GROQ_MAX_RETRIES = 2
GROQ_TIMEOUT_SECONDS = 60.0
GROQ_SDK_VERSION = version("groq")

_SENSITIVE_ENV_NAMES = (
    "GROQ_API_KEY",
    "GEMINI_API_KEY",
    "DATABASE_URL",
    "SECRET_KEY",
)
_SECRET_ASSIGNMENT_PATTERN = re.compile(
    r"(?i)\b(api[_-]?key|authorization|database_url|secret_key|password|token)"
    r"(\s*[:=]\s*)([^,\s}\]]+)"
)
_SECRET_QUERY_PATTERN = re.compile(r"(?i)([?&](?:key|token)=)[^&\s]+")
_AUTHORIZATION_BEARER_PATTERN = re.compile(
    r"(?i)\b(authorization\s*[:=]\s*bearer\s+)[^,\s}\]]+"
)


class GroqGenerationError(Exception):
    """A reply could not be generated by Groq."""


def _redact_text(value: Any, protected_values: tuple[str, ...]) -> str | None:
    if value is None:
        return None

    text = str(value)
    for secret_name in _SENSITIVE_ENV_NAMES:
        secret_value = os.getenv(secret_name)
        if secret_value:
            text = text.replace(secret_value, "[REDACTED]")
    for protected_value in protected_values:
        if protected_value:
            text = text.replace(protected_value, "[REDACTED]")
    text = _AUTHORIZATION_BEARER_PATTERN.sub(r"\1[REDACTED]", text)
    text = _SECRET_ASSIGNMENT_PATTERN.sub(r"\1\2[REDACTED]", text)
    text = _SECRET_QUERY_PATTERN.sub(r"\1[REDACTED]", text)
    return text[:1000]


def _safe_error_metadata(
    exc: Exception, protected_values: tuple[str, ...]
) -> dict[str, Any]:
    metadata: dict[str, Any] = {
        "error_type": type(exc).__name__,
        "provider_message": _redact_text(
            getattr(exc, "message", None) or str(exc), protected_values
        ),
    }
    status_code = getattr(exc, "status_code", None)
    if status_code is not None:
        metadata["status_code"] = status_code

    response = getattr(exc, "response", None)
    headers = getattr(response, "headers", None)
    if headers is not None:
        request_id = headers.get("x-request-id")
        retry_after = headers.get("retry-after")
        if request_id:
            metadata["request_id"] = _redact_text(request_id, protected_values)
        if retry_after:
            metadata["retry_after"] = _redact_text(retry_after, protected_values)

    body = getattr(exc, "body", None)
    if isinstance(body, dict):
        error = body.get("error", body)
        if isinstance(error, dict):
            for source_key, output_key in (
                ("type", "provider_error_type"),
                ("code", "provider_error_code"),
                ("param", "provider_error_param"),
            ):
                value = error.get(source_key)
                if isinstance(value, (str, int, float, bool)):
                    metadata[output_key] = _redact_text(value, protected_values)
    return metadata


def _log_generation_error(
    exc: Exception, system_context: str, user_message: str
) -> None:
    protected_values = (system_context, user_message)
    context_bytes = system_context.encode("utf-8")
    metadata = _safe_error_metadata(exc, protected_values)
    logger.error(
        "Groq generation failed: model=%s sdk_version=%s max_retries=%s "
        "timeout_seconds=%s request_shape=system+user conversation_history=false "
        "context_chars=%s context_bytes=%s context_sha256=%s "
        "user_message_chars=%s user_message_bytes=%s error_type=%s "
        "status_code=%s provider_error_type=%s provider_error_code=%s "
        "provider_error_param=%s request_id=%s retry_after=%s provider_message=%s",
        GROQ_MODEL,
        GROQ_SDK_VERSION,
        GROQ_MAX_RETRIES,
        GROQ_TIMEOUT_SECONDS,
        len(system_context),
        len(context_bytes),
        hashlib.sha256(context_bytes).hexdigest()[:16],
        len(user_message),
        len(user_message.encode("utf-8")),
        metadata.get("error_type"),
        metadata.get("status_code"),
        metadata.get("provider_error_type"),
        metadata.get("provider_error_code"),
        metadata.get("provider_error_param"),
        metadata.get("request_id"),
        metadata.get("retry_after"),
        metadata.get("provider_message"),
    )


def generate_reply(system_context: str, user_message: str) -> str:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.error("Groq generation failed: GROQ_API_KEY is not configured")
        raise GroqGenerationError("Groq API key is not configured")

    try:
        with Groq(
            api_key=api_key,
            max_retries=GROQ_MAX_RETRIES,
            timeout=GROQ_TIMEOUT_SECONDS,
        ) as client:
            completion = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[
                    {"role": "system", "content": system_context},
                    {"role": "user", "content": user_message},
                ],
                include_reasoning=False,
                reasoning_effort="low",
                max_completion_tokens=1024,
            )
            reply = completion.choices[0].message.content
    except groq.RateLimitError as exc:
        _log_generation_error(exc, system_context, user_message)
        raise GroqGenerationError("Groq is temporarily rate limited") from exc
    except (groq.APITimeoutError, groq.APIConnectionError) as exc:
        _log_generation_error(exc, system_context, user_message)
        raise GroqGenerationError("Groq is temporarily unreachable") from exc
    except groq.APIError as exc:
        _log_generation_error(exc, system_context, user_message)
        raise GroqGenerationError("Groq could not generate a reply") from exc
    except Exception as exc:
        _log_generation_error(exc, system_context, user_message)
        raise GroqGenerationError("Groq returned an invalid response") from exc

    if not reply or not reply.strip():
        raise GroqGenerationError("Groq returned an empty reply")
    return reply.strip()
